config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user do
    mount Motor::Admin => '/admin'
  end
  resources :projects, only: %i[index show]
  resources :chapters, only: %i[index show]
  resources :countries, only: %i[index show]
  devise_for :users, controllers: {
    registrations: 'users/registrations' # Override devise registration controller
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'landing#index'

  get 'about_us', to: 'landing#about', as: :landing_about
  get 'learn', to: 'landing#learn', as: :landing_learn
end

app/models/country.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: countries
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Country < ApplicationRecord
  # Associations
  has_many :chapters, dependent: :nullify

  # Callbacks
  after_create_commit lambda {
                        broadcast_prepend_to 'countries', partial: 'countries/created_country',
                                                          locals: { country: self }, target: 'countries'
                      }

  after_update_commit lambda {
                        broadcast_update_to 'countries', partial: 'countries/updated_country',
                                                         locals: { country: self }, target: self
                      }

  after_destroy_commit -> { broadcast_remove_to 'countries', target: self }

  # Validations
  validates :name, presence: true
end

app/controllers/countries_controller.rb
# frozen_string_literal: true

class CountriesController < ApplicationController
  before_action :set_country, only: %i[show]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_country
    @country = Country.find(params[:id])
  end
end

app/helpers/countries_helper.rb
# frozen_string_literal: true

module CountriesHelper
end

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>
</div>

app/views/countries/_created_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>
</div>

app/views/countries/_new_country.html.erb
<div class="table-body-cell">
  <%= country.name %>
</div>
<div class="table-body-cell flex inline space-x-1 justify-start">
  <%= link_to 'Edit', edit_country_path(country), class: 'btn btn-xs btn-info' %>
  <%= button_to 'Delete', country, class: 'btn btn-xs btn-error',
                method: :delete, data: { turbo_frame: "_top" } %>
</div>

app/views/countries/index.html.erb
<%= turbo_stream_from "countries" %>

<div class="container pt-10">
  <h1 class="text-4xl pt-6 pb-16 font-bold">
    Countries
  </h1>

  <div class="overflow-x-auto">
    <%= turbo_frame_tag Country.new %>
    <div class="container">
      <div class="resp-table">
        <div class="resp-table-body">
          <div class="resp-table-row">
            <div class="table-body-cell">
              <b>Name</b>
            </div>
            <div class="table-body-cell">
              <b>Actions</b>
            </div>
          </div>
        </div>

        <%= turbo_frame_tag :countries, class: "resp-table-body" do %>
          <% @countries.each do |country| %>
            <%= turbo_frame_tag country, class: "resp-table-row" do %>
              <div class="table-body-cell">
                <%= country.name %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>