config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  authenticate :user do
    mount Motor::Admin => '/admin'
  end
  resources :projects, only: %i[index show]
  resources :chapters, only: %i[index show]
  resources :countries, only: %i[index show]
  devise_for :users, controllers: {
    registrations: 'users/registrations' # Override devise registration controller
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'landing#index'

  get 'about_us', to: 'landing#about', as: :landing_about
  get 'learn', to: 'landing#learn', as: :landing_learn
end

app/views/layouts/_flash_messages.html.erb
<div class="toast toast-top toast-end" id="flash_messages">
  <% if notice || alert %>
    <%= content_tag :div,
                    class: "alert #{ alert ? 'alert-error' : 'alert-success'} alert_custom_class",
                    data: { controller: 'removals',
                            action: 'animationend->removals#remove click->removals#remove_on_click' } do %>

      <!--  Display flash icon on the left-->
      <% if notice %>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6"
             fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6
        2a9 9 0 11-18 0 9 9 0 0118 0z"/>
      <% elsif alert %>
        <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current flex-shrink-0 h-6 w-6"
             fill="none" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0
        0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
      <% end %>

      <div><%= content_tag :span, notice || alert %></div>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer aria-labelledby="footer-heading" class="md:pt-32 pt-24 px-8 md:px-20 lg:ml-20">
  <div class="grid md:grid-cols-3 gap-12 justify-center items-center text-center md:text-left">
    <%= link_to root_path, class: "flex justify-center md:justify-end md:pr-20" do %>
      <%= image_tag('arc_logo_coloured.png', alt: "Community Logo", class: 'w-32 md:w-48') %>
    <% end %>

    <ul class="flex flex-col gap-3">
      <li  class="hover:text-red-600 hover:underline"><%= link_to 'Home', root_path %></li>
      <% if FeatureFlag.find_by(name: 'events').try(:enabled) %>
        <li class="hover:text-red-600 hover:underline"><%= link_to 'Events', '#' %></li>
      <% end %>

      <li class="hover:text-red-600 hover:underline"><%= link_to 'Chapters', chapters_path %></li>

      <li class="hover:text-red-600 hover:underline"><%= link_to 'Learning materials', landing_learn_path %></li>

      <% if FeatureFlag.find_by(name: 'projects').try(:enabled) %>
        <li class="hover:text-red-600 hover:underline"><%= link_to 'Projects', '#' %></li>
      <% end %>
    </ul>

    <ul class="flex flex-col gap-3">
      <li class="hover:text-red-600 hover:underline"><%= link_to 'Sponsor', 'mailto:organisers@rubycommunity.africa' %></li>

      <% if FeatureFlag.find_by(name: 'members').try(:enabled) %>
        <li class="hover:text-red-600 hover:underline"><%= link_to 'Members', '#' %></li>
      <% end %>

      <li class="hover:text-red-600 hover:underline"><%= link_to 'About', landing_about_path %></li>

      <% if FeatureFlag.find_by(name: 'contact_us').try(:enabled) %>
        <li class="hover:text-red-600 hover:underline"><%= link_to 'Contact Us', '#' %></li>
      <% end %>

      <% if FeatureFlag.find_by(name: 'contact_us').try(:enabled) %>
        <li class="hover:text-red-600 hover:underline"><%= link_to 'Code of conduct', '#' %></li>
      <% end %>
    </ul>
  </div>

  <div class="flex flex-col justify-center items-center pt-12">
      <h1 class="pt-4 pb-12 md:text-4xl text-2xl text-red-600 font-bold text-center">
        Connect
      </h1>
      <ul class="flex md:flex-row flex-col md:mt-4 md:gap-10 gap-5">
        <% socials.each do |social| %>
          <% if social[:show] === true %>
            <li class='md:border-2 border-red-600 p-5 rounded-full'>
              <%= link_to social[:link] do %>
                <%= image_tag social[:image], alt: social[:alt], class: "md:w-5 w-8 hover:scale-105" %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
  </div>

  <p class="text-center pt-10 pb-10">All Rights Reserved. African Ruby Community. Copyright <%= Date.today.year %></p>
</footer>

app/views/layouts/_navbar.html.erb
<navbar class="sticky top-0 z-50 font-inter">
  <div class="relative bg-gray-50  border-red-400">
    <div class="mx-auto flex max-w-7xl items-center justify-between px-4 py-2 sm:px-6
  md:justify-start md:space-x-10 lg:px-8">
      <div class="dropdown">
        <label tabindex="0" class="btn btn-ghost md:hidden">
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"/>
          </svg>
        </label>
        <ul tabindex="0" class="menu menu-compact dropdown-content mt-3 p-2 shadow
        bg-base-100 rounded-box w-52 md:hidden ">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About ARC', landing_about_path %></li>

          <% if FeatureFlag.find_by(name: 'events').try(:enabled) %>
            <li><a href="#">Events</a></li>
          <% end %>

          <li><%= link_to 'Chapters', chapters_path %></li>

          <% if FeatureFlag.find_by(name: 'projects').try(:enabled) %>
            <li><a href="#">Projects</a></li>
          <% end %>

          <li><%= link_to 'Learning Materials', landing_learn_path %></li>

          <% if user_signed_in? %>
            <li><%= button_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
      <div class="flex justify-start lg:w-0 lg:flex-1">
        <%= link_to root_path do %>
          <span class="sr-only">African Ruby Community</span>
          <%= image_tag('arc_logo_coloured.png', alt: "Community Logo",class: "h-8 w-auto sm:h-7") %>
        <% end %>
      </div>
      <nav class="hidden space-x-10 md:flex font-semibold text-gray-800 text-sm py-4">
        <%= link_to 'Home', root_path,
                    class: " hover:text-red-600" %>
        <%= link_to 'About', landing_about_path,
                    class: "hover:text-red-600" %>

        <% if FeatureFlag.find_by(name: 'events').try(:enabled) %>
          <a href="#" class="text-sm font-small hover:text-red-600">Events</a>
        <% end %>

        <% if FeatureFlag.find_by(name: 'conferences').try(:enabled) %>
          <a href="#" class="hover:text-red-600">
            Conferences
          </a>
        <% end %>

        <%= link_to 'Chapters', chapters_path,
                    class: "hover:text-red-600" %>

        <% if FeatureFlag.find_by(name: 'projects').try(:enabled) %>
          <a href="#" class="hover:text-red-600">
            Projects
          </a>
        <% end %>

        <%= link_to 'Learning Materials', landing_learn_path,
                    class: 'hover:text-red-600' %>
      </nav>
      <% if user_signed_in? %>

        <div class="hidden items-center justify-end md:flex md:flex-1 lg:w-0">
          <% if current_user.organization_admin? %>
            <div class="dropdown dropdown-end">
              <button class="hover:text-red-600">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                      viewBox="0 0 24 24" fill="none" stroke="currentColor"
                      stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                      class="feather feather-settings">
                  <circle cx="12" cy="12" r="3">
                  </circle>
                  <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0
                1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0
                1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0
                0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0
                .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0
                0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83
                0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2
                0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0
                1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0
                1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path>
                </svg>
              </button>
              <ul tabindex="0" class="menu dropdown-content p-2 shadow bg-base-100 rounded-box
              w-52 mt-4">
                <li>
                  <div class="grid grid-cols-1 divide-y">
                    <b>Settings</b>
                    <div/>
                  </div>
                </li>
                <li>
                  <%= link_to 'Countries', countries_path %>
                </li>
                <li>
                  <%= link_to 'Chapters', chapters_path %>
                </li>
              </ul>
            </div>
          <% end %>

          <div class="dropdown dropdown-end ml-8">
            <button class="hover:text-red-600">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                    viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"
                    stroke-linecap="round" stroke-linejoin="round" class="feather feather-user">
                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
            </button>
            <ul tabindex="0" class="menu dropdown-content p-2 shadow bg-base-100 rounded-box w-52 mt-4">
              <li>
                <%= link_to 'Update profile', edit_user_registration_path %>
              </li>
            </ul>
          </div>

          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "whitespace-nowrap text-sm font-small text-gray-500
        hover:text-red-700 ml-8" %>
        </div>
      <% else %>
        <div class="hidden items-center justify-end md:flex md:flex-1 lg:w-0">
          <%= link_to new_user_session_path do %>
            <button class="border-2 border-red-600 rounded-full py-1 px-3 text-sm flex justify-center items-center normal-case text-red-600 hover:bg-red-600 hover:text-white font-semibold">Sign in</button>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</navbar>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>ArcPlatform <%= " - " + yield(:title) if content_for?(:title)%></title>
  <meta name="description" content=<%= content_for?(:description) ? yield(:description) : "African Ruby Community, ARC is an organization that was started in 2010. The community currently has over reach of over 5,000 members spread across East Africa, made of developers (Engineers),entrepreneurs, designers and freelancers."%>>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag 'favicon.ico' %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body>
  <div class="bg-gray-50">

    <%= render 'layouts/navbar' %>

    <main class="mx-8" style="min-height: 45vh">
      <%= yield %>
    </main>

    <%= render 'layouts/flash_messages' %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>